export type Character = {
  id: string;
  name: string;
  image: string;
};

export const characters: Character[] = [
  { id: "bayonetta", name: "ベヨネッタ", image: "/characters/bayonetta.png" },
  { id: "brave", name: "勇者", image: "/characters/brave.png" },
  { id: "buddy", name: "バンジョー＆カズーイ", image: "/characters/buddy.png" },
  { id: "captain", name: "キャプテン・ファルコン", image: "/characters/captain.png" },
  { id: "chrom", name: "クロム", image: "/characters/chrom.png" },
  { id: "cloud", name: "クラウド", image: "/characters/cloud.png" },
  { id: "daisy", name: "デイジー", image: "/characters/daisy.png" },
  { id: "dedede", name: "デデデ", image: "/characters/dedede.png" },
  { id: "demon", name: "カズヤ", image: "/characters/demon.png" },
  { id: "diddy", name: "ディディーコング", image: "/characters/diddy.png" },
  { id: "dolly", name: "テリー", image: "/characters/dolly.png" },
  { id: "donkey", name: "ドンキーコング", image: "/characters/donkey.png" },
  { id: "duckhunt", name: "ダックハント", image: "/characters/duckhunt.png" },
  { id: "edge", name: "セフィロス", image: "/characters/edge.png" },
  { id: "eflame", name: "ホムラ／ヒカリ", image: "/characters/eflame.png" },
  { id: "falco", name: "ファルコ", image: "/characters/falco.png" },
  { id: "fox", name: "フォックス", image: "/characters/fox.png" },
  { id: "gamewatch", name: "Mr.ゲーム＆ウォッチ", image: "/characters/gamewatch.png" },
  { id: "ganon", name: "ガノンドロフ", image: "/characters/ganon.png" },
  { id: "gaogaen", name: "ガオガエン", image: "/characters/gaogaen.png" },
  { id: "gekkouga", name: "ゲッコウガ", image: "/characters/gekkouga.png" },
  { id: "ice_climber", name: "アイスクライマー", image: "/characters/ice_climber.png" },
  { id: "ike", name: "アイク", image: "/characters/ike.png" },
  { id: "inkling", name: "インクリング", image: "/characters/inkling.png" },
  { id: "jack", name: "ジョーカー", image: "/characters/jack.png" },
  { id: "kamui", name: "カムイ", image: "/characters/kamui.png" },
  { id: "ken", name: "ケン", image: "/characters/ken.png" },
  { id: "kirby", name: "カービィ", image: "/characters/kirby.png" },
  { id: "koopa", name: "クッパ", image: "/characters/koopa.png" },
  { id: "koopajr", name: "クッパJr.", image: "/characters/koopajr.png" },
  { id: "krool", name: "キングクルール", image: "/characters/krool.png" },
  { id: "link", name: "リンク", image: "/characters/link.png" },
  { id: "littlemac", name: "リトル・マック", image: "/characters/littlemac.png" },
  { id: "lucario", name: "ルカリオ", image: "/characters/lucario.png" },
  { id: "lucas", name: "リュカ", image: "/characters/lucas.png" },
  { id: "lucina", name: "ルキナ", image: "/characters/lucina.png" },
  { id: "luigi", name: "ルイージ", image: "/characters/luigi.png" },
  { id: "mario", name: "マリオ", image: "/characters/mario.png" },
  { id: "mariod", name: "ドクターマリオ", image: "/characters/mariod.png" },
  { id: "marth", name: "マルス", image: "/characters/marth.png" },
  { id: "master", name: "ベレト／ベレス", image: "/characters/master.png" },
  { id: "metaknight", name: "メタナイト", image: "/characters/metaknight.png" },
  { id: "mewtwo", name: "ミュウツー", image: "/characters/mewtwo.png" },
  { id: "murabito", name: "むらびと", image: "/characters/murabito.png" },
  { id: "ness", name: "ネス", image: "/characters/ness.png" },
  { id: "packun", name: "パックンフラワー", image: "/characters/packun.png" },
  { id: "pacman", name: "パックマン", image: "/characters/pacman.png" },
  { id: "palutena", name: "パルテナ", image: "/characters/palutena.png" },
  { id: "peach", name: "ピーチ", image: "/characters/peach.png" },
  { id: "pichu", name: "ピチュー", image: "/characters/pichu.png" },
  { id: "pickel", name: "スティーブ", image: "/characters/pickel.png" },
  { id: "pikachu", name: "ピカチュウ", image: "/characters/pikachu.png" },
  { id: "pikmin", name: "ピクミン＆オリマー", image: "/characters/pikmin.png" },
  { id: "pit", name: "ピット", image: "/characters/pit.png" },
  { id: "pitb", name: "ブラックピット", image: "/characters/pitb.png" },
  { id: "ptrainer", name: "ポケモントレーナー", image: "/characters/ptrainer.png" },
  { id: "purin", name: "プリン", image: "/characters/purin.png" },
  { id: "reflet", name: "ルフレ", image: "/characters/reflet.png" },
  { id: "richter", name: "リヒター", image: "/characters/richter.png" },
  { id: "ridley", name: "リドリー", image: "/characters/ridley.png" },
  { id: "robot", name: "ロボット", image: "/characters/robot.png" },
  { id: "rockman", name: "ロックマン", image: "/characters/rockman.png" },
  { id: "rosetta", name: "ロゼッタ＆チコ", image: "/characters/rosetta.png" },
  { id: "roy", name: "ロイ", image: "/characters/roy.png" },
  { id: "ryu", name: "リュウ", image: "/characters/ryu.png" },
  { id: "samus", name: "サムス", image: "/characters/samus.png" },
  { id: "samusd", name: "ダークサムス", image: "/characters/samusd.png" },
  { id: "sheik", name: "シーク", image: "/characters/sheik.png" },
  { id: "shizue", name: "しずえ", image: "/characters/shizue.png" },
  { id: "shulk", name: "シュルク", image: "/characters/shulk.png" },
  { id: "simon", name: "シモン", image: "/characters/simon.png" },
  { id: "snake", name: "スネーク", image: "/characters/snake.png" },
  { id: "sonic", name: "ソニック", image: "/characters/sonic.png" },
  { id: "szerosuit", name: "ゼロスーツサムス", image: "/characters/szerosuit.png" },
  { id: "tantan", name: "ミェンミェン", image: "/characters/tantan.png" },
  { id: "toonlink", name: "トゥーンリンク", image: "/characters/toonlink.png" },
  { id: "trail", name: "ソラ", image: "/characters/trail.png" },
  { id: "wario", name: "ワリオ", image: "/characters/wario.png" },
  { id: "wiifit", name: "Wii Fit トレーナー", image: "/characters/wiifit.png" },
  { id: "wolf", name: "ウルフ", image: "/characters/wolf.png" },
  { id: "yoshi", name: "ヨッシー", image: "/characters/yoshi.png" },
  { id: "younglink", name: "こどもリンク", image: "/characters/younglink.png" },
  { id: "zelda", name: "ゼルダ", image: "/characters/zelda.png" },
];